import aritmetica as a
import text as t

print(a.Sum(2,-3))
print(a.Rest(1,-2))
print(a.Mult(1123,5))
print(a.Div(100,2))
print(a.Pot(20,5))
print(a.Rad(70))
print(a.Tan(76))
print(a.Sin(45))
print(a.Cos(59))
print(a.Tan(66))
print(a.Log(8544))
print(t.concat("Hola ","Mundo"))
print(t.concat("Buenas ","tardes"))
print(t.concat("Feliz "," Dia"))
print(t.concat("Mi Nombre Es"," Pepe"))

print ("Dime un numero")
primerNumero = int(input())
print ("Dime otro numero")
segundoNumero = int(input())
print ("Su suma es")
print (a.Sum(primerNumero,segundoNumero))

print("Raiz de")
n = float(input())
print ("Su raíz es")
print (a.Rad(n))

print ("Multiplicacion de")
primerNumero = int(input())
print ("Dime otro numero")
segundoNumero = int(input())
print ("Su multiplicacion es")
print (a.Mult(primerNumero,segundoNumero))

print ("Potencia de")
primerNumero = int(input())
print ("Dime otro numero")
segundoNumero = int(input())
print ("Su potencia es")
print (a.Pot(primerNumero,segundoNumero))

print ("resta de")
primerNumero = int(input())
print ("Dime otro numero")
segundoNumero = int(input())
print ("Su resta es")
print (a.Rest(primerNumero,segundoNumero))

print ("Division de")
primerNumero = int(input())
print ("Dime otro numero")
segundoNumero = int(input())
print ("Su division es")
print (a.Div(primerNumero,segundoNumero))

print ("tangente de")
primerNumero = int(input())
print ("Su tangente es")
print (a.Tan(n))

print("logaritmo de")
primerNumero = int(input())
print("Su logaritmo es")
print(a.Log(n))